CREATE TABLE StyleCodes (
    -- PersonID int,
    -- LastName varchar(255),
    -- FirstName varchar(255),
    -- Address varchar(255),
    -- City varchar(255)

    id int AUTO_INCREMENT,
    styleCode varchar(255) NOT NULL,
    buyer varchar(255),
    brand varchar(255),
    season varchar(255),
    salesChannel varchar(255),
    product varchar(255),
    productType varchar(255),
    productCategory varchar(255),
    productColor varchar(255),
    productMRP int,
    styleDescription varchar(255),
    fitType varchar(255),
    collarType varchar(255),
    sleeveType varchar(255),
    fabricContent varchar(255),
    fabricPattern varchar(255),
    fabricWeave varchar(255),
    fabricWash varchar(255),
    orderNo varchar(255),
    confirmDate varchar(255),
    orderQty int,
    makeQty int,
    deliveryDate varchar(255),
    unitSellingPrice int,
    xsSizeQty int,
    sSizeQty int,
    mSizeQty int,
    xlSizeQty int,
    xxlSizeQty int,
    styleCodeStatus varchar(255),
   	PRIMARY KEY (id)
);