export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_COMPLETE_TASKS = "FETCH_COMPLETE_TASKS";
export const FETCH_INCOMPLETE_TASKS = "FETCH_INCOMPLETE_TASKS";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";